### ISSUE TITLE
Getting an error when running PirateRadio.py

### ISSUE THREAD

**Issue by Linkje** [Make-Magazine/PirateRadio#19]
I'm getting an error when running the script for the first time. I tried it on a Raspberry Pi B and a B+ and I get the same error. 

Traceback (most recent call last):
  File "PirateRadio.py", line 176, in <module>
    main()
  File "PirateRadio.py", line 31, in main
    setup()
  File "PirateRadio.py", line 148, in setup
    read_config()
  File "PirateRadio.py", line 94, in read_config
    frequency = config.get("pirateradio",'frequency')
  File "/usr/local/lib/python2.7/dist-packages/backports/configparser/**init**.py", line 786, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1164, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'pirateradio'

What am i doing wrong. I didn't change anything to the code.

**Comment by cydactyl** [comment]
The application is hardcoded to check `/pirateradio/pirateradio.conf`. If you go into the PirateRadio.py file and change line 17 to wherever you placed the config file it should work correctly. If that is not the problem and the config file is located in `/pirateradio/` then you need to check `pirateradio.conf` and confirm that the `[pirateradio]` block is unaltered.

Alternatively you can place the files into the `/pirateradio` directory as defined in the script.

**Comment by ric96** [comment]
still cant get it to work
[root@alarmpi pirateradio]# python PirateRadio.py
Traceback (most recent call last):
  File "PirateRadio.py", line 180, in <module>
    main()
  File "PirateRadio.py", line 35, in main
    setup()
  File "PirateRadio.py", line 152, in setup
    read_config()
  File "PirateRadio.py", line 97, in read_config
    play_stereo = config.get("pirateradio", 'stereo_playback', fallback=True)
TypeError: get() got an unexpected keyword argument 'fallback'
[root@alarmpi pirateradio]#

**Comment by ric96** [comment]
[root@alarmpi pirateradio]# Traceback (most recent call last):
  File "PirateRadio.py", line 180, in <module>
    main()
  File "PirateRadio.py", line 35, in main
    setup()
  File "PirateRadio.py", line 154, in setup
    run_pifm()
  File "PirateRadio.py", line 160, in run_pifm
    fm_process = subprocess.Popen(["pifm","-",str(frequency),"44100", "stereo" if play_stereo else "mono"], stdin=music_pipe_r, stdout=dev_null)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[root@alarmpi pirateradio]#

**Comment by avrovulcanxh607** [comment]
I get this problem:
Traceback (most recent call last) :
    File "/pirateradio/PirateRadio.py", line 180, in <module>
       main()
    File "/pirateradio/PirateRadio.py", line 34, in main
       deamonize ()
    File "/pirateradio/PirateRadio.py", line 145, in deamonize
       sys.exit (0)
SystemExit: 0

I don't know what's wrong, HELP!!!

**Comment by isfanl** [comment]
i got this error when executing PirateRadio.py

pi@raspberrypi:~/PirateRadio $ python PirateRadio.py
Traceback (most recent call last):
File "PirateRadio.py", line 180, in 
main()
File "PirateRadio.py", line 35, in main
setup()
File "PirateRadio.py", line 152, in setup
read_config()
File "PirateRadio.py", line 97, in read_config
play_stereo = config.get("pirateradio", 'stereo_playback', fallback=True)
TypeError: get() got an unexpected keyword argument 'fallback'
pi@raspberrypi:~/PirateRadio $

what should i do ?

**Comment by cydactyl** [comment]
try some of the tips from this issue, https://github.com/Make-Magazine/PirateRadio/issues/13
